export default {
    "LOGIN": "LOGIN",
    "UPDATE_FB_PROFILE_PICTURE": "UPDATE_FB_PROFILE_PICTURE",
    "UPDATE_ALBUMS": "UPDATE_ALBUMS",
    "UPDATE_THUMBNAILS": "UPDATE_THUMBNAILS",
    "UPDATE_ALBUMS_PHOTOS" : "UPDATE_ALBUMS_PHOTOS"
}